
##################################################
# Radar Sources
##################################################
WAVEGEN_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/wavegen/, \
bram_stream_wrapper.v \
waveform_dds.v \
waveform_decoder.v \
waveform_stream.v \
wavegen_block.v \
chirpgen.v \
wavegen_regs.vh \
noc_block_wavegen.v \
radar_pulse_controller.v \
rx_command_gen.v \
axi_burst_packetizer.v \
axi_burst_header_packetizer.v \
axi_stream_buffer.v \
axi_pulse_mux.v \
))
