#
# Copyright 2014 Ettus Research LLC
#

##################################################
# RFNoC Sources
##################################################
RFNOC_OOT_SRCS = $(AWG_SRCS) $(CIRAVG_SRCS) $(PULSECIRAVG_SRCS) \


