
##################################################
# Radar Sources
##################################################
WAVEGEN_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/wavegen/, \
bram_stream_wrapper.v \
waveform_dds.v \
waveform_formatter.v \
waveform_stream.v \
wavegen_block.v \
chirpgen.v \
)
